import type { StoredProduct } from './localStorage';

export const SEED_PRODUCTS: Omit<StoredProduct, 'productId' | 'sku'>[] = [
  {
    productName: 'Coca Cola 330ml',
    category: 'Beverages',
    metricValue: '330ml',
    price: 150,
    stockQuantity: 120,
  },
  {
    productName: 'Pepsi 330ml',
    category: 'Beverages',
    metricValue: '330ml',
    price: 140,
    stockQuantity: 95,
  },
  {
    productName: 'Sprite 330ml',
    category: 'Beverages',
    metricValue: '330ml',
    price: 145,
    stockQuantity: 80,
  },
  {
    productName: 'Orange Juice 1L',
    category: 'Beverages',
    metricValue: '1L',
    price: 350,
    stockQuantity: 40,
  },
  {
    productName: 'Wireless Mouse',
    category: 'Electronics',
    metricValue: '',
    price: 1250,
    stockQuantity: 25,
  },
  {
    productName: 'USB-C Cable 2m',
    category: 'Electronics',
    metricValue: '2m',
    price: 450,
    stockQuantity: 60,
  },
  {
    productName: 'Bluetooth Speaker',
    category: 'Electronics',
    metricValue: '',
    price: 3200,
    stockQuantity: 15,
  },
  {
    productName: 'Fresh Milk 1L',
    category: 'Fresh Dairy',
    metricValue: '1L',
    price: 420,
    stockQuantity: 30,
  },
  {
    productName: 'Yogurt 500g',
    category: 'Fresh Dairy',
    metricValue: '500g',
    price: 280,
    stockQuantity: 45,
  },
  {
    productName: 'Cheddar Cheese 200g',
    category: 'Fresh Dairy',
    metricValue: '200g',
    price: 650,
    stockQuantity: 20,
  },
  {
    productName: 'Mixed Vegetables 1kg',
    category: 'Frozen',
    metricValue: '1kg',
    price: 380,
    stockQuantity: 35,
  },
  {
    productName: 'Chicken Nuggets 500g',
    category: 'Frozen',
    metricValue: '500g',
    price: 890,
    stockQuantity: 25,
  },
  {
    productName: 'Ice Cream Vanilla 1L',
    category: 'Frozen',
    metricValue: '1L',
    price: 750,
    stockQuantity: 18,
  },
  {
    productName: 'White Rice 5kg',
    category: 'Rice',
    metricValue: '5kg',
    price: 1250,
    stockQuantity: 50,
  },
  {
    productName: 'Basmati Rice 2kg',
    category: 'Rice',
    metricValue: '2kg',
    price: 980,
    stockQuantity: 30,
  },
  {
    productName: 'Keeri Samba 5kg',
    category: 'Rice',
    metricValue: '5kg',
    price: 1450,
    stockQuantity: 40,
  },
];